Repository ureca-itPlace/itplace-user-api, pull requests merged in 2025-08, with the labels that each got.

#176 feat: 보유 쿠폰 개수 조회
  src/main/java/com/itplace/userapi/user/UserCode.java
  src/main/java/com/itplace/userapi/user/controller/UserCouponController.java
  src/main/java/com/itplace/userapi/user/service/UserService.java
  src/main/java/com/itplace/userapi/user/service/UserServiceImpl.java
  src/main/resources/static/swagger.yml
Labels: ✨ Feature

#177 feat: 쿠폰 사용 이력, 필터링
  src/main/java/com/itplace/userapi/event/GiftCode.java
  src/main/java/com/itplace/userapi/event/controller/GiftController.java
  src/main/java/com/itplace/userapi/event/dto/HistoryResponse.java
  src/main/java/com/itplace/userapi/event/exception/InvalidResultTypeException.java
  src/main/java/com/itplace/userapi/event/service/CouponHistoryService.java
  src/main/java/com/itplace/userapi/event/service/CouponHistoryServiceImpl.java
  src/main/resources/static/swagger.yml
Labels: ✨ Feature

#179 [Refactor] 추천 서비스 구조 변경
  src/main/java/com/itplace/userapi/recommend/controller/RecommendationController.java
  src/main/java/com/itplace/userapi/recommend/service/OpenAiRecommendationService.java
  src/main/java/com/itplace/userapi/recommend/service/RecommendationService.java
  src/main/java/com/itplace/userapi/recommend/service/RecommendationServiceImpl.java
  src/main/java/com/itplace/userapi/recommend/strategy/OpenAiRankingStrategy.java
  src/main/java/com/itplace/userapi/recommend/strategy/OpenAiRetrievalStrategy.java
  src/main/java/com/itplace/userapi/recommend/strategy/RankingStrategy.java
  src/main/java/com/itplace/userapi/recommend/strategy/RetrievalStrategy.java
Labels: 🛠️ Refactor

#181 [Fix] 이벤트 이력 오류 수정
  src/main/java/com/itplace/userapi/event/service/CouponHistoryServiceImpl.java
Labels: 🛠️ Refactor

#185 [Fix] CICD 수정
  .github/workflows/CICD.yml
  .github/workflows/main_deploy.yml
Labels: 👾 Bug

#187 [Feat] 회원가입 비밀번호 validation 추가
  src/main/java/com/itplace/userapi/security/auth/local/dto/request/SignUpRequest.java
Labels: ✨ Feature

#191 [Refactor] 추천 이유 수정 및 이벤트 확률 조정
  src/main/java/com/itplace/userapi/event/service/ScratchServiceImpl.java
  src/main/java/com/itplace/userapi/log/LogAnalysisController.java
  src/main/java/com/itplace/userapi/log/dto/LogScoreResult.java
  src/main/java/com/itplace/userapi/log/dto/PartnerNameResult.java
  src/main/java/com/itplace/userapi/log/repository/CustomLogRepository.java
  src/main/java/com/itplace/userapi/log/repository/CustomLogRepositoryImpl.java
  src/main/java/com/itplace/userapi/log/service/LogService.java
  src/main/java/com/itplace/userapi/log/service/LogServiceImpl.java
  src/main/java/com/itplace/userapi/recommend/domain/UserFeature.java
  src/main/java/com/itplace/userapi/recommend/service/OpenAIServiceImpl.java
  src/main/java/com/itplace/userapi/recommend/service/UserFeatureServiceImpl.java
Labels: 🛠️ Refactor

#192 fix: 지도 파라미터 추가
  src/main/java/com/itplace/userapi/ai/question/service/QuestionRecommendationServiceImpl.java
  src/main/java/com/itplace/userapi/map/controller/StoreController.java
  src/main/java/com/itplace/userapi/map/service/StoreService.java
  src/main/java/com/itplace/userapi/map/service/StoreServiceImpl.java
Labels: 🛠️ Refactor

#194 [Refactor] ChangeModel
  src/main/java/com/itplace/userapi/recommend/service/OpenAIServiceImpl.java
  src/main/java/com/itplace/userapi/recommend/service/RecommendationServiceImpl.java
Labels: 🛠️ Refactor

#195 [Fix] 오류 정상화
  src/main/java/com/itplace/userapi/map/service/StoreServiceImpl.java
Labels: 👾 Bug
